version: '3.7'

services:

    redis:
        image: redis:alpine
        container_name: ${PROJECT_NAME}-redis
        restart: always
        networks:
            - ${PROJECT_NAME}

    mariadb:
        container_name: ${PROJECT_NAME}-mariadb
        image: mariadb:10.5
        working_dir: /application
        command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --innodb-file-format=Barracuda, --innodb-large-prefix=1, --innodb-file-per-table=1]
        volumes:
            - ./db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        restart: always
        networks:
            - ${PROJECT_NAME}

    nginx:
        image: nginx:latest
        container_name: ${PROJECT_NAME}-nginx
        depends_on:
            - php-fpm
        ports:
            - ${WEB_PORT_HOST}:${WEB_PORT_CONTAINER}
        volumes:
            - ./www:/var/www/html
            - ./docker-config/nginx-pimcore.conf:/etc/nginx/nginx.conf
        restart: always
        networks:
            - ${PROJECT_NAME}

    php-fpm:
        image: pimcore/pimcore:PHP8.0-fpm-buster
        container_name: ${PROJECT_NAME}-php-fpm
        environment:
            - "TZ=Europe/Berlin"
        depends_on:
            - mariadb
        volumes:
            - ./www:/var/www/html
            - ./docker-config/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./docker-config/30-pimcore-php.ini:/usr/local/etc/php/conf.d/30-pimcore-php.ini
        restart: always
        networks:
            - ${PROJECT_NAME}

    nginx-debug:
        image: nginx:latest
        container_name: ${PROJECT_NAME}-nginx-debug
        depends_on:
            - php-fpm-debug
        ports:
            - "2006:80"
        volumes:
            - ./www:/var/www/html
            - ./docker-config/nginx-pimcore-debug.conf:/etc/nginx/nginx.conf
        networks:
            - ${PROJECT_NAME}

    php-fpm-debug:
        image: pimcore/pimcore:PHP8.0-fpm-buster-debug
        container_name: ${PROJECT_NAME}-php-fpm-debug
        environment:
            - "TZ=Europe/Berlin"
        depends_on:
            - mariadb
        volumes:
            - ./www:/var/www/html
            - ./docker-config/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./docker-config/30-pimcore-php.ini:/usr/local/etc/php/conf.d/30-pimcore-php.ini
        networks:
            - ${PROJECT_NAME}

networks:
    pimcorex:
        name: ${PROJECT_NAME}
        driver: bridge
